#!/usr/bin/env python3
import json
import requests
import os
import colorama
from colorama import Fore, Style

#######################################################################################
#Please enter your API keys below. Make sure to insert inbetween the "Quotation Marks".
#######################################################################################
global API_KEY_ADDRESS, API_KEY_EMAIL, API_KEY_PHONE
API_KEY_ADDRESS = ("")
API_KEY_EMAIL = ("")
API_KEY_PHONE = ("")

class color:
    PURPLE = '\033[95m'
    CYAN = '\033[96m'
    DARKCYAN = '\033[36m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    END = '\033[0m'

os.system("cls||clear")

def main():
    while True:
        print (Fore.YELLOW + "█████", end="")
        print ("██", Fore.WHITE + "╗", Fore.YELLOW + "██████", Fore.WHITE + "╗  ", sep="", end="")
        print (Fore.YELLOW + "  ██", Fore.WHITE + "╗", Fore.YELLOW + "\n██", Fore.WHITE + "╔════╝", Fore.YELLOW + "██", Fore.WHITE + "╔", sep="", end="")
        print ("══", Fore.YELLOW + "██", Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n█████", Fore.WHITE + "╗", Fore.YELLOW + "  ███", sep="", end="")
        print ("███", Fore.WHITE + "╔╝", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "╔══╝", Fore.YELLOW + "  ██", Fore.WHITE + "╔══", Fore.YELLOW + "██", sep="", end="")
        print (Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "║", Fore.WHITE + "█", sep="", end="")
        print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "  ████", sep="", end="")
        print ("██", Fore.WHITE + "╔╝", Fore.WHITE + "█", sep="", end="")
        print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "█", sep="", end="")
        print ("█", Fore.WHITE + "║", Fore.WHITE + "██╗", sep ="")
        print ("╚═╝" + Fore.WHITE + "╚═", end="")
        print ("╝" + Fore.WHITE + "  ╚══", end="")
        print ("═══╝" + Fore.WHITE + " ", end="")
        print ("╚═╝" + Fore.WHITE + "╚═╝", Fore.WHITE + "╚═╝", sep="", end=" ")
        print (Fore.WHITE + "by", Fore.YELLOW + color.BOLD + "Jack Carter", color.END)
        print (Fore.YELLOW + "Find", Fore.WHITE + ".", sep="", end="    ")
        print (Fore.YELLOW + "Big", Fore.WHITE + ".", sep="", end="     ")
        print (Fore.YELLOW + "Info", Fore.WHITE + ".", sep="", end="")
        print ("\n \n \n")
        print (Fore.WHITE + color.BOLD + "[", Fore.YELLOW + "1", Fore.WHITE + "]", sep="", end=" ")
        print (Fore.WHITE + color.BOLD + "Reverse Search Address\n ", color.END)
        print (Fore.WHITE + color.BOLD + "[", Fore.YELLOW + "2", Fore.WHITE + "]", sep="", end=" ")
        print (Fore.WHITE + color.BOLD + "Reverse Search Email Address\n ", color.END)
        print (Fore.WHITE + color.BOLD + "[", Fore.YELLOW + "3", Fore.WHITE + "]", sep="", end=" ")
        print (Fore.WHITE + color.BOLD + "Reverse Search Phone Number\n \n \n", color.END)
        direct_choice = input(Fore.WHITE + "Please choose by " + Fore.YELLOW + color.BOLD + "number " + color.END + Fore.WHITE + "or type " + Fore.YELLOW + color.BOLD + "exit " + color.END + Fore.WHITE + "to close: " + Fore.YELLOW + color.BOLD) 
        if direct_choice == ("1"):
            os.system("cls||clear")
            address_line_1 = input(Style.RESET_ALL + '*HIT ENTER TO LEAVE BLANK*\n' + Fore.YELLOW + '---------------------------\n \n' + Fore.WHITE + color.BOLD + 'Address Line 1: ' + Fore.YELLOW)
            new_line_1 = (address_line_1.replace(" ", "+"))
            print (Fore.WHITE + color.BOLD)
            address_line_2 = input('Address Line 2: ' + Fore.YELLOW)
            new_line_2 = (address_line_2.replace(" ", "+"))
            print (Fore.WHITE + color.BOLD)
            city = input('City: ' + Fore.YELLOW)
            new_city = (city.replace(" ", "+"))
            print (Fore.WHITE + color.BOLD)
            state_code = input('State code: ' + Fore.YELLOW)
            print (Fore.WHITE + color.BOLD)
            post_code = input('Postal Code: ' + Fore.YELLOW)
            new_post_code = (post_code.replace(" ", ""))
            print (Fore.WHITE + color.BOLD)
            country_code = input('Country code ' + Fore.WHITE + '(Eg: ' + Fore.YELLOW + color.BOLD + 'US' + Fore.WHITE + ',' + Fore.YELLOW + ' UK' + Fore.WHITE + ' etc.): ' + Fore.YELLOW)
            print ("")
            url = ('https://api.ekata.com/3.0/location?api_key=' + API_KEY_ADDRESS + '&street_line_1=' + new_line_1 + '&street_line_2=' + new_line_2 + '&city=' + new_city + '&state_code=' + state_code + '&postal_code=' + new_post_code + '&country_code=' + country_code)
            response = requests.get(url)
            todos = json.loads(response.text)
            sc = response.status_code
            if sc == 200:
                    while True:
                        try:
                            os.system("cls||clear")
                            var_street_1 = str(todos['street_line_1'])
                            var_street_2 = str(todos['street_line_2'])
                            var_city = str(todos['city'])
                            var_postal_code = str(todos['postal_code'])
                            var_state_code = str(todos['state_code'])
                            var_country_code = str(todos['country_code'])
                            print (Fore.WHITE + color.BOLD + "**********************************************************************************************************************")
                            print ("")
                            print (color.BOLD + Fore.WHITE + "ADDRESS")
                            print ("------------")
                            print ("\n ")
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Street Line 1:", Fore.WHITE + var_street_1)
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Street Line 2:", Fore.WHITE + var_street_2)
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "City:", Fore.WHITE + var_city)
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Postal Code:", Fore.WHITE + var_postal_code)
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "State Code:", Fore.WHITE + var_state_code)
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Country Code:", Fore.WHITE + var_country_code)
                            print ("\n ")
                            print (Fore.WHITE + "RESIDENTS")
                            print ("------------")
                            print ("\n ")
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['name'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['firstname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Middle Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['middlename'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['lastname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Alternate Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['alternate_names'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Age Range:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['age_range'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Gender:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['gender'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Type:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['type'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Industry:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['industry'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Link to Address/Start Date:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['link_to_address_start_date'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Phone Numbers:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['phones'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Historical Addresses:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['historical_addresses'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Associated People:", Fore.WHITE, end="")
                            print (todos['current_residents'][0]['associated_people'])
                            print ("\n ")
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['name'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['firstname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Middle Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['middlename'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['lastname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Alternate Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['alternate_names'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Age Range:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['age_range'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Gender:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['gender'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Type:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['type'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Industry:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['industry'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Link to Address/Start Date:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['link_to_address_start_date'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Phone Numbers:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['phones'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Historical Addresses:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['historical_addresses'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Associated People:", Fore.WHITE, end="")
                            print (todos['current_residents'][1]['associated_people'])
                            print ("\n ")
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['name'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['firstname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Middle Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['middlename'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['lastname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Alternate Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['alternate_names'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Age Range:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['age_range'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Gender:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['gender'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Type:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['type'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Industry:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['industry'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Link to Address/Start Date:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['link_to_address_start_date'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Phone Numbers:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['phones'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Historical Addresses:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['historical_addresses'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Associated People:", Fore.WHITE, end="")
                            print (todos['current_residents'][2]['associated_people'])
                            print ("\n ")
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['name'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['firstname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Middle Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['middlename'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['lastname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Alternate Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['alternate_names'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Age Range:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['age_range'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Gender:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['gender'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Type:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['type'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Industry:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['industry'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Link to Address/Start Date:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['link_to_address_start_date'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Phone Numbers:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['phones'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Historical Addresses:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['historical_addresses'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Associated People:", Fore.WHITE, end="")
                            print (todos['current_residents'][3]['associated_people'])
                            print ("\n ")
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['name'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['firstname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Middle Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['middlename'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['lastname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Alternate Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['alternate_names'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Age Range:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['age_range'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Gender:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['gender'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Type:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['type'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Industry:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['industry'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Link to Address/Start Date:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['link_to_address_start_date'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Phone Numbers:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['phones'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Historical Addresses:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['historical_addresses'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Associated People:", Fore.WHITE, end="")
                            print (todos['current_residents'][4]['associated_people'])
                            print ("\n ")
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['name'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['firstname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Middle Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['middlename'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['lastname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Alternate Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['alternate_names'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Age Range:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['age_range'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Gender:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['gender'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Type:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['type'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Industry:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['industry'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Link to Address/Start Date:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['link_to_address_start_date'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Phone Numbers:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['phones'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Historical Addresses:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['historical_addresses'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Associated People:", Fore.WHITE, end="")
                            print (todos['current_residents'][5]['associated_people'])
                            print ("\n ")
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['name'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['firstname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Middle Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['middlename'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['lastname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Alternate Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['alternate_names'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Age Range:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['age_range'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Gender:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['gender'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Type:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['type'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Industry:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['industry'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Link to Address/Start Date:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['link_to_address_start_date'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Phone Numbers:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['phones'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Historical Addresses:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['historical_addresses'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Associated People:", Fore.WHITE, end="")
                            print (todos['current_residents'][6]['associated_people'])
                            print ("\n ")
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['name'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['firstname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Middle Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['middlename'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['lastname'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Alternate Names:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['alternate_names'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Age Range:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['age_range'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Gender:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['gender'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Type:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['type'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Industry:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['industry'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Link to Address/Start Date:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['link_to_address_start_date'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Phone Numbers:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['phones'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Historical Addresses:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['historical_addresses'])
                            print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                            print (Fore.YELLOW + "Associated People:", Fore.WHITE, end="")
                            print (todos['current_residents'][7]['associated_people'])
                            print ("")
                            break
                        except IndexError:
                            print ("\n \n")
                            print (Fore.WHITE + "END OF RESULTS\n")
                            print (Fore.WHITE + color.BOLD + "**********************************************************************************************************************")
                            print ("\n ")
                            back_close = input(color.END + Fore.WHITE + 'Type ' + Fore.YELLOW + color.BOLD + 'back ' + color.END + Fore.WHITE + 'to return to directory. Otherwise, hit' + Fore.YELLOW + color.BOLD + ' any key' + color.END + Fore.WHITE + ' to close the script: ' + Fore.YELLOW + color.BOLD)
                            if back_close == ("back"):
                                print (color.END)
                                os.system("cls||clear")
                                main ()
                                break
                            else:
                                print (color.END)
                                os.system("cls||clear")
                                print (Fore.YELLOW + "█████", end="")
                                print ("██", Fore.WHITE + "╗", Fore.YELLOW + "██████", Fore.WHITE + "╗  ", sep="", end="")
                                print (Fore.YELLOW + "  ██", Fore.WHITE + "╗", Fore.YELLOW + "\n██", Fore.WHITE + "╔════╝", Fore.YELLOW + "██", Fore.WHITE + "╔", sep="", end="")
                                print ("══", Fore.YELLOW + "██", Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n█████", Fore.WHITE + "╗", Fore.YELLOW + "  ███", sep="", end="")
                                print ("███", Fore.WHITE + "╔╝", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "╔══╝", Fore.YELLOW + "  ██", Fore.WHITE + "╔══", Fore.YELLOW + "██", sep="", end="")
                                print (Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "║", Fore.WHITE + "█", sep="", end="")
                                print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "  ████", sep="", end="")
                                print ("██", Fore.WHITE + "╔╝", Fore.WHITE + "█", sep="", end="")
                                print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "█", sep="", end="")
                                print ("█", Fore.WHITE + "║", Fore.WHITE + "██╗", sep ="")
                                print ("╚═╝" + Fore.WHITE + "╚═", end="")
                                print ("╝" + Fore.WHITE + "  ╚══", end="")
                                print ("═══╝" + Fore.WHITE + " ", end="")
                                print ("╚═╝" + Fore.WHITE + "╚═╝", Fore.WHITE + "╚═╝", sep="", end=" ")
                                print (Fore.WHITE + "by", Fore.YELLOW + color.BOLD + "Jack Carter", color.END)
                                print (Fore.YELLOW + "Find", Fore.WHITE + ".", sep="", end="    ")
                                print (Fore.YELLOW + "Big", Fore.WHITE + ".", sep="", end="     ")
                                print (Fore.YELLOW + "Info", Fore.WHITE + ".", sep="", end="")
                                print ("\n")
                                break
            return
        elif direct_choice == ("2"):
            os.system("cls||clear")
            email_address = input(Fore.WHITE + color.BOLD + 'Email Address: ' + Fore.YELLOW)
            new_email = (email_address.replace("@", "%40"))
            url = ('https://api.ekata.com/4.1/email?api_key=' + API_KEY_EMAIL + '&email_address=' + new_email)
            response = requests.get(url)
            todos = json.loads(response.text)
            sc = response.status_code
            if sc == 200:
                while True:
                    try:
                        os.system("cls||clear")
                        print (Fore.WHITE + color.BOLD + "**********************************************************************************************************************")
                        print ("")
                        print (Fore.WHITE + "EMAIL ADDRESS\n----------------\n")
                        var_email_address = str(todos['email_address'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Email Address:", Fore.WHITE + var_email_address)
                        print ("\n \n")
                        print (Fore.WHITE + "PERSONAL INFO\n----------------\n")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Registered Owner:", Fore.WHITE, end="")
                        print (todos['registered_owner']['name'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                        print (todos['registered_owner']['firstname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Middle Name:", Fore.WHITE, end="")
                        print (todos['registered_owner']['middlename'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                        print (todos['registered_owner']['lastname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Alternate Names:", Fore.WHITE, end="")
                        print (todos['registered_owner']['alternate_names'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Age Range:", Fore.WHITE, end="")
                        print (todos['registered_owner']['age_range'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Gender:", Fore.WHITE, end="")
                        print (todos['registered_owner']['gender'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Type:", Fore.WHITE, end="")
                        print (todos['registered_owner']['type'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Phone Number:", Fore.WHITE, end="")
                        print (todos['phones'])
                        print ("\n ")
                        print (Fore.WHITE + "CURRENT ADDRESSES\n------------------\n")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Street Line 1:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['street_line_1'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Street Line 2:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['street_line_2'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "City:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['city'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Postal Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['postal_code'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "State Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['state_code'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Country Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['country_code'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Link To Person Start Date:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['link_to_person_start_date'])
                        print ("")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Street Line 1:", Fore.WHITE, end="")
                        print (todos['current_addresses'][1]['street_line_1'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Street Line 2:", Fore.WHITE, end="")
                        print (todos['current_addresses'][1]['street_line_2'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "City:", Fore.WHITE, end="")
                        print (todos['current_addresses'][1]['city'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Postal Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][1]['postal_code'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "State Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][1]['state_code'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Country Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][1]['country_code'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Link To Person Start Date:", Fore.WHITE, end="")
                        print (todos['current_addresses'][1]['link_to_person_start_date'])
                        print ("")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Street Line 1:", Fore.WHITE, end="")
                        print (todos['current_addresses'][2]['street_line_1'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Street Line 2:", Fore.WHITE, end="")
                        print (todos['current_addresses'][2]['street_line_2'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "City:", Fore.WHITE, end="")
                        print (todos['current_addresses'][2]['city'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Postal Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][2]['postal_code'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "State Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][2]['state_code'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Country Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][2]['country_code'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Link To Person Start Date:", Fore.WHITE, end="")
                        print (todos['current_addresses'][2]['link_to_person_start_date'])
                        print ("\n \n")
                        break
                    except IndexError:
                        print ("")
                        print ("")
                        print (Fore.WHITE + "END OF RESULTS\n")
                        print (Fore.WHITE + color.BOLD + "**********************************************************************************************************************\n")
                        back_close = input(color.END + Fore.WHITE + 'Type ' + Fore.YELLOW + color.BOLD + 'back ' + color.END + Fore.WHITE + 'to return to directory. Otherwise, hit' + Fore.YELLOW + color.BOLD + ' any key' + color.END + Fore.WHITE + ' to close the script: ' + Fore.YELLOW + color.BOLD)
                        if back_close == ("back"):
                            print (color.END)
                            os.system("cls||clear")
                            main ()
                            break
                        else:
                            print (color.END)
                            os.system("cls||clear")
                            print (Fore.YELLOW + "█████", end="")
                            print ("██", Fore.WHITE + "╗", Fore.YELLOW + "██████", Fore.WHITE + "╗  ", sep="", end="")
                            print (Fore.YELLOW + "  ██", Fore.WHITE + "╗", Fore.YELLOW + "\n██", Fore.WHITE + "╔════╝", Fore.YELLOW + "██", Fore.WHITE + "╔", sep="", end="")
                            print ("══", Fore.YELLOW + "██", Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n█████", Fore.WHITE + "╗", Fore.YELLOW + "  ███", sep="", end="")
                            print ("███", Fore.WHITE + "╔╝", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "╔══╝", Fore.YELLOW + "  ██", Fore.WHITE + "╔══", Fore.YELLOW + "██", sep="", end="")
                            print (Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "║", Fore.WHITE + "█", sep="", end="")
                            print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "  ████", sep="", end="")
                            print ("██", Fore.WHITE + "╔╝", Fore.WHITE + "█", sep="", end="")
                            print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "█", sep="", end="")
                            print ("█", Fore.WHITE + "║", Fore.WHITE + "██╗", sep ="")
                            print ("╚═╝" + Fore.WHITE + "╚═", end="")
                            print ("╝" + Fore.WHITE + "  ╚══", end="")
                            print ("═══╝" + Fore.WHITE + " ", end="")
                            print ("╚═╝" + Fore.WHITE + "╚═╝", Fore.WHITE + "╚═╝", sep="", end=" ")
                            print (Fore.WHITE + "by", Fore.YELLOW + color.BOLD + "Jack Carter", color.END)
                            print (Fore.YELLOW + "Find", Fore.WHITE + ".", sep="", end="    ")
                            print (Fore.YELLOW + "Big", Fore.WHITE + ".", sep="", end="     ")
                            print (Fore.YELLOW + "Info", Fore.WHITE + ".", sep="", end="")
                            print ("\n")
                            break
                    except TypeError:
                            print ("NO RESULTS FOUND\n")
                            print (Fore.WHITE + color.BOLD + "**********************************************************************************************************************\n")
                            back_close = input(color.END + Fore.WHITE + 'Type ' + Fore.YELLOW + color.BOLD + 'back ' + color.END + Fore.WHITE + 'to return to directory. Otherwise, hit' + Fore.YELLOW + color.BOLD + ' any key' + color.END + Fore.WHITE + ' to close the script: ' + Fore.YELLOW + color.BOLD)
                            if back_close == ("back"):
                                print (color.END)
                                os.system("cls||clear")
                                main ()
                                break
                            else:
                                print (color.END)
                                os.system("cls||clear")
                                print (Fore.YELLOW + "█████", end="")
                                print ("██", Fore.WHITE + "╗", Fore.YELLOW + "██████", Fore.WHITE + "╗  ", sep="", end="")
                                print (Fore.YELLOW + "  ██", Fore.WHITE + "╗", Fore.YELLOW + "\n██", Fore.WHITE + "╔════╝", Fore.YELLOW + "██", Fore.WHITE + "╔", sep="", end="")
                                print ("══", Fore.YELLOW + "██", Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n█████", Fore.WHITE + "╗", Fore.YELLOW + "  ███", sep="", end="")
                                print ("███", Fore.WHITE + "╔╝", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "╔══╝", Fore.YELLOW + "  ██", Fore.WHITE + "╔══", Fore.YELLOW + "██", sep="", end="")
                                print (Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "║", Fore.WHITE + "█", sep="", end="")
                                print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "  ████", sep="", end="")
                                print ("██", Fore.WHITE + "╔╝", Fore.WHITE + "█", sep="", end="")
                                print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "█", sep="", end="")
                                print ("█", Fore.WHITE + "║", Fore.WHITE + "██╗", sep ="")
                                print ("╚═╝" + Fore.WHITE + "╚═", end="")
                                print ("╝" + Fore.WHITE + "  ╚══", end="")
                                print ("═══╝" + Fore.WHITE + " ", end="")
                                print ("╚═╝" + Fore.WHITE + "╚═╝", Fore.WHITE + "╚═╝", sep="", end=" ")
                                print (Fore.WHITE + "by", Fore.YELLOW + color.BOLD + "Jack Carter", color.END)
                                print (Fore.YELLOW + "Find", Fore.WHITE + ".", sep="", end="    ")
                                print (Fore.YELLOW + "Big", Fore.WHITE + ".", sep="", end="     ")
                                print (Fore.YELLOW + "Info", Fore.WHITE + ".", sep="", end="")
                                print ("\n")
                                break

            return
        elif direct_choice == ("3"):
            os.system("cls||clear")
            phone_area = input(Fore.WHITE + color.BOLD + 'Area code \n(Eg: ' + Fore.YELLOW + color.BOLD + '+44 ' + Fore.WHITE + color.BOLD + 'etc. Must include even for landline): ' + Fore.YELLOW)
            print ("")
            phone_num = input(Fore.WHITE + color.BOLD + 'Phone number: ' + Fore.YELLOW)
            phone_number = (phone_area + phone_num)
            url = ('https://api.ekata.com/3.1/phone?api_key=' + API_KEY_PHONE + '&phone=' + phone_number)
            response = requests.get(url)
            todos = json.loads(response.text)
            sc = response.status_code
            if sc == 200:
                while True:
                    try:
                        os.system("cls||clear")
                        print (Fore.WHITE + color.BOLD + "**********************************************************************************************************************")
                        print ("")
                        print (Fore.WHITE + "PHONE NUMBER\n--------------\n")
                        var_phone_number = str(todos['phone_number'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Phone Number:", Fore.WHITE, end="")
                        print (var_phone_number)
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Is Valid:", Fore.WHITE, end="")
                        print (todos['is_valid'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Carrier:", Fore.WHITE, end="")
                        print (todos['carrier'])
                        print ("")
                        print (Fore.WHITE + "BELONGS TO\n--------------\n")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                        print (todos['belongs_to']['name'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                        print (todos['belongs_to']['firstname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Middle Name:", Fore.WHITE, end="")
                        print (todos['belongs_to']['middlename'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                        print (todos['belongs_to']['lastname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Age Range:", Fore.WHITE, end="")
                        print (todos['belongs_to']['age_range'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Gender:", Fore.WHITE, end="")
                        print (todos['belongs_to']['gender'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.WHITE + "Link To Phone Start Date:", Fore.WHITE, end="")
                        print (todos['belongs_to']['link_to_phone_start_date'])
                        print ("")
                        print ("")
                        print (Fore.WHITE + "CURRENT ADDRESSES\n----------------------\n")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW  + "Street Line 1:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['street_line_1'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Street Line 2:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['street_line_2'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "City:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['city'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Postal Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['postal_code'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "State Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['state_code'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Country Code:", Fore.WHITE, end="")
                        print (todos['current_addresses'][0]['country_code'])
                        print ("")
                        print ("")
                        print (Fore.WHITE + "ASSOCIATED PEOPLE\n--------------------\n")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][0]['name'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][0]['firstname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Middle Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][0]['middlename'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][0]['lastname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Relation To Home Owner:", Fore.WHITE, end="")
                        print (todos['associated_people'][0]['relation'])
                        print ("")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][1]['name'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][1]['firstname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Middle Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][1]['middlename'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][1]['lastname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Relation To Home Owner:", Fore.WHITE, end="")
                        print (todos['associated_people'][1]['relation'])
                        print ("")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][2]['name'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][2]['firstname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Middle Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][2]['middlename'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][2]['lastname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Relation To Home Owner:", Fore.WHITE, end="")
                        print (todos['associated_people'][2]['relation'])
                        print ("")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][3]['name'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][3]['firstname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Middle Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][3]['middlename'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][3]['lastname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Relation To Home Owner:", Fore.WHITE, end="")
                        print (todos['associated_people'][3]['relation'])
                        print ("")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][4]['name'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][4]['firstname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Middle Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][4]['middlename'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][4]['lastname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Relation To Home Owner:", Fore.WHITE, end="")
                        print (todos['associated_people'][4]['relation'])
                        print ("")
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][5]['name'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "First Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][5]['firstname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Middle Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][5]['middlename'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Last Name:", Fore.WHITE, end="")
                        print (todos['associated_people'][5]['lastname'])
                        print (Fore.YELLOW + "{", Fore.BLUE + "*", Fore.YELLOW + "}", sep="", end=" ")
                        print (Fore.YELLOW + "Relation To Home Owner:", Fore.WHITE, end="")
                        print (todos['associated_people'][5]['relation'])
                        print ("")
                    except IndexError:
                        print ("\n \n")
                        print (Fore.WHITE + "END OF RESULTS\n")
                        print (Fore.WHITE + color.BOLD + "**********************************************************************************************************************\n")
                        back_close = input(color.END + Fore.WHITE + 'Type ' + Fore.YELLOW + color.BOLD + 'back ' + color.END + Fore.WHITE + 'to return to directory. Otherwise, hit' + Fore.YELLOW + color.BOLD + ' any key' + color.END + Fore.WHITE + ' to close the script: ' + Fore.YELLOW + color.BOLD)
                        if back_close == ("back"):
                            print (color.END)
                            os.system("cls||clear")
                            main ()
                            break
                        else:
                            print (color.END)
                            os.system("cls||clear")
                            print (Fore.YELLOW + "█████", end="")
                            print ("██", Fore.WHITE + "╗", Fore.YELLOW + "██████", Fore.WHITE + "╗  ", sep="", end="")
                            print (Fore.YELLOW + "  ██", Fore.WHITE + "╗", Fore.YELLOW + "\n██", Fore.WHITE + "╔════╝", Fore.YELLOW + "██", Fore.WHITE + "╔", sep="", end="")
                            print ("══", Fore.YELLOW + "██", Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n█████", Fore.WHITE + "╗", Fore.YELLOW + "  ███", sep="", end="")
                            print ("███", Fore.WHITE + "╔╝", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "╔══╝", Fore.YELLOW + "  ██", Fore.WHITE + "╔══", Fore.YELLOW + "██", sep="", end="")
                            print (Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "║", Fore.WHITE + "█", sep="", end="")
                            print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "  ████", sep="", end="")
                            print ("██", Fore.WHITE + "╔╝", Fore.WHITE + "█", sep="", end="")
                            print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "█", sep="", end="")
                            print ("█", Fore.WHITE + "║", Fore.WHITE + "██╗", sep ="")
                            print ("╚═╝" + Fore.WHITE + "╚═", end="")
                            print ("╝" + Fore.WHITE + "  ╚══", end="")
                            print ("═══╝" + Fore.WHITE + " ", end="")
                            print ("╚═╝" + Fore.WHITE + "╚═╝", Fore.WHITE + "╚═╝", sep="", end=" ")
                            print (Fore.WHITE + "by", Fore.YELLOW + color.BOLD + "Jack Carter", color.END)
                            print (Fore.YELLOW + "Find", Fore.WHITE + ".", sep="", end="    ")
                            print (Fore.YELLOW + "Big", Fore.WHITE + ".", sep="", end="     ")
                            print (Fore.YELLOW + "Info", Fore.WHITE + ".", sep="", end="")
                            print ("\n")
                            break
                    except TypeError:
                        print (Fore.WHITE + "NO RESULTS FOUND\n")
                        print (Fore.WHITE + color.BOLD + "**********************************************************************************************************************\n")
                        back_close = input(color.END + Fore.WHITE + 'Type ' + Fore.YELLOW + color.BOLD + 'back ' + color.END + Fore.WHITE + 'to return to directory. Otherwise, hit' + Fore.YELLOW + color.BOLD + ' any key' + color.END + Fore.WHITE + ' to close the script: ' + Fore.YELLOW + color.BOLD)
                        if back_close == ("back"):
                            print (color.END)
                            os.system("cls||clear")
                            main ()
                            break
                        else:
                            print (color.END)
                            os.system("cls||clear")
                            print (Fore.YELLOW + "█████", end="")
                            print ("██", Fore.WHITE + "╗", Fore.YELLOW + "██████", Fore.WHITE + "╗  ", sep="", end="")
                            print (Fore.YELLOW + "  ██", Fore.WHITE + "╗", Fore.YELLOW + "\n██", Fore.WHITE + "╔════╝", Fore.YELLOW + "██", Fore.WHITE + "╔", sep="", end="")
                            print ("══", Fore.YELLOW + "██", Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n█████", Fore.WHITE + "╗", Fore.YELLOW + "  ███", sep="", end="")
                            print ("███", Fore.WHITE + "╔╝", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "╔══╝", Fore.YELLOW + "  ██", Fore.WHITE + "╔══", Fore.YELLOW + "██", sep="", end="")
                            print (Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "║", Fore.WHITE + "█", sep="", end="")
                            print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "  ████", sep="", end="")
                            print ("██", Fore.WHITE + "╔╝", Fore.WHITE + "█", sep="", end="")
                            print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "█", sep="", end="")
                            print ("█", Fore.WHITE + "║", Fore.WHITE + "██╗", sep ="")
                            print ("╚═╝" + Fore.WHITE + "╚═", end="")
                            print ("╝" + Fore.WHITE + "  ╚══", end="")
                            print ("═══╝" + Fore.WHITE + " ", end="")
                            print ("╚═╝" + Fore.WHITE + "╚═╝", Fore.WHITE + "╚═╝", sep="", end=" ")
                            print (Fore.WHITE + "by", Fore.YELLOW + color.BOLD + "Jack Carter", color.END)
                            print (Fore.YELLOW + "Find", Fore.WHITE + ".", sep="", end="    ")
                            print (Fore.YELLOW + "Big", Fore.WHITE + ".", sep="", end="     ")
                            print (Fore.YELLOW + "Info", Fore.WHITE + ".", sep="", end="")
                            print ("\n")
                            break
            return
        elif direct_choice == ("exit"):
            print (color.END)
            os.system("cls||clear")
            print (Fore.YELLOW + "█████", end="")
            print ("██", Fore.WHITE + "╗", Fore.YELLOW + "██████", Fore.WHITE + "╗  ", sep="", end="")
            print (Fore.YELLOW + "  ██", Fore.WHITE + "╗", Fore.YELLOW + "\n██", Fore.WHITE + "╔════╝", Fore.YELLOW + "██", Fore.WHITE + "╔", sep="", end="")
            print ("══", Fore.YELLOW + "██", Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n█████", Fore.WHITE + "╗", Fore.YELLOW + "  ███", sep="", end="")
            print ("███", Fore.WHITE + "╔╝", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "╔══╝", Fore.YELLOW + "  ██", Fore.WHITE + "╔══", Fore.YELLOW + "██", sep="", end="")
            print (Fore.WHITE + "╗", Fore.YELLOW + "   ██", Fore.WHITE + "║", Fore.YELLOW + "\n██", Fore.WHITE + "║", Fore.WHITE + "█", sep="", end="")
            print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "  ████", sep="", end="")
            print ("██", Fore.WHITE + "╔╝", Fore.WHITE + "█", sep="", end="")
            print (Fore.WHITE + "█", Fore.WHITE + "╗", Fore.YELLOW + "█", sep="", end="")
            print ("█", Fore.WHITE + "║", Fore.WHITE + "██╗", sep ="")
            print ("╚═╝" + Fore.WHITE + "╚═", end="")
            print ("╝" + Fore.WHITE + "  ╚══", end="")
            print ("═══╝" + Fore.WHITE + " ", end="")
            print ("╚═╝" + Fore.WHITE + "╚═╝", Fore.WHITE + "╚═╝", sep="", end=" ")
            print (Fore.WHITE + "by", Fore.YELLOW + color.BOLD + "Jack Carter", color.END)
            print (Fore.YELLOW + "Find", Fore.WHITE + ".", sep="", end="    ")
            print (Fore.YELLOW + "Big", Fore.WHITE + ".", sep="", end="     ")
            print (Fore.YELLOW + "Info", Fore.WHITE + ".", sep="", end="")
            print ("\n")
            break
        else:
            print (color.END)
            os.system("cls||clear")
if __name__ == "__main__":
    main ()
